---
title: "Advanced Econometrics 2 Assignment 1 Problem 3"
author: "Brian DeVoe"
output: pdf_document
date: "2024-02-13"
---

-------------------------------------------------
# Problem 3a

$Y_t = c + \phi_1Y_{t-1} + \phi_2Y_{t-2} + \epsilon_t + \theta\epsilon_{t-1}$

$(Y_t - \mu) = \phi_1(Y_{t-1} - \mu) + \phi_2(Y_{t-2} - \mu) + \epsilon_t + \theta\epsilon_{t-1}$

&nbsp;

$E(Y_t - \mu)(Y_t - \mu) = E(Y_t - \mu)^2 = \phi_1E(Y_{t-1} - \mu)(Y_t - \mu) + \phi_2E(Y_{t-2} - \mu)(Y_t- \mu) + E[\epsilon(Y_t - \mu)] + \theta E[\epsilon_{t-1}(Y_t - \mu)]$

&nbsp;

$\gamma_0 = \phi_1\gamma_1 + \phi_2\gamma_2 + E[\epsilon_t (Y_t - \mu)] + \theta E[\epsilon_{t-1}(Y_t - \mu)]$

&nbsp;

$E[\epsilon_t (Y_t - \mu)] = \sigma^2$

&nbsp;

$\theta E[\epsilon_{t-1}(Y_t - \mu)] = \theta E(\epsilon_{t-1}\phi_1y_{t-1}) + \theta E(\epsilon_{t-1}\phi_2y_{t-2}) + \theta E(\epsilon_{t-1}\theta \epsilon_{t-1}) + \theta E(\epsilon_{t-1}\epsilon_t)$

$= \theta^2E(\epsilon_{t-1}^2) = \theta\phi_1 E(\epsilon_{t-1}y_{t-1}) + 0 + 0$

$= \theta^2\sigma^2 + \theta\phi_1 E(\epsilon_{t-1}y_{t-1})$

$= \theta^2\sigma^2 + \theta\phi_1E[\epsilon_{t-1}(\phi_1y_{t-2}+\phi_2y_{t-2} + \epsilon_{t-1} \theta\epsilon_{t-2})]$

$= \theta^2\sigma^2 + \theta\phi_1 \sigma^2$

&nbsp;

$\gamma_0 = \phi_1 \gamma_1 + \theta_2 \gamma_2 + \sigma^2 + \theta\phi_1 \sigma^2$

&nbsp;
&nbsp;

$\gamma_1 = E(Y_t -\mu)(Y_{t-1} = \mu) = \phi_1 E(Y_{t-1}-\mu)(Y_{t-1}-\mu) + \phi_2 E(Y_{t-2} - \mu)(Y_{t-1} - \mu) + E[\epsilon(Y_{t-1} - \mu)] + \theta E[\epsilon_{t-1}(Y_{t-1} - \mu)]$ 

&nbsp;

$\gamma_1 = \phi_1 \gamma_0 + \phi_2 \gamma_1 + \theta\sigma^2$

&nbsp;

$\gamma_2 = E(Y_t - \mu)(Y_{t-2} - \mu) = \phi_1 E(Y_{t-1} - \mu)(Y_{t-2} - \mu) + \phi_2 E(Y_{t-2} - \mu)(Y_{t-2} - \mu) + E[\epsilon_t(Y_{t-2} - \mu)] + \theta E[\epsilon_{t-1}(Y_{t-2} - \mu)]$

$\gamma_2 = \phi_1\gamma_1 + \phi_2\gamma_0$

&nbsp;

for n > 2

&nbsp;

$\gamma_n = \phi_1\gamma_{n-1} + \phi_2\gamma_{n-2}$




